[build]
  # This is the directory to change to before starting a build.
  base    = "frontend"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "frontend/build/"
  # This will be your default build command
  command = "yarn run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
